import { ECalendarValue, IDatePickerConfig } from "ng2-date-picker";

export const DatePickerDefault: IDatePickerConfig = {
  firstDayOfWeek: "su",
  monthFormat: "MMM, YYYY",
  disableKeypress: true,
  closeOnSelect: true,
  closeOnSelectDelay: 0,
  openOnFocus: false,
  openOnClick: false,
  onOpenDelay: 100,
  closeOnEnter: true,
  weekDayFormat: "ddd",
  showNearMonthDays: false,
  showWeekNumbers: false,
  enableMonthSelector: true,
  yearFormat: "YYYY",
  showGoToCurrent: false,
  dayBtnFormat: "DD",
  monthBtnFormat: "MMM",
  hours12Format: "hh",
  hours24Format: "HH",
  meridiemFormat: "A",
  minutesFormat: "mm",
  minutesInterval: 1,
  secondsFormat: "ss",
  secondsInterval: 1,
  showSeconds: false,
  showTwentyFourHours: true,
  timeSeparator: ":",
  multipleYearsNavigateBy: 10,
  showMultipleYearsNavigation: false,
  hideInputContainer: true,
  returnedValueType: ECalendarValue.String,
  unSelectOnClick: true,
  hideOnOutsideClick: true,
  numOfMonthRows: 3,
  locale: "pt-br",
  format: "DD/MM/YYYY HH:mm",
};
