export const Exceptions = {
  userNotAuthorized: "Usuário não autorizado",
  negativeNumber: "O valor pago não pode ser negativo.",
  invalidNumber: "Valor invalido.",
  invalidField: "Campo invalido.",
  invalidName: "Nome inválido.",
  invalidUsername: "Nome de usuario inválido.",
  invalidNameLength: "Nome deve conter no mínimo 3 dígitos.",
  invalidEmail: "Email inválido.",
  emailExists: "Email já existe.",
  incorrectPassword: "Senha incorreta.",
  invalidPassword: "Senha inválida.",
  invalidPasswordLength: "Senha deve conter no mínimo 6 dígitos",
  invalidPasswordConfirmation: "Confirmação de senha não coincide.",
  cannotFindUser: "Email não cadastrado.",
  error: "Erro inesperado.",
  titleInvalid: "Título inválido.",
  dateInvalid: "É obrigatório selecionar a data do pagamento.",
  updateUserSuccess: "As informações do usuário foram editadas com sucesso",
  updateUserError: "Ocorreu um erro ao editar o usuário.",
};
